//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParagonAccountsNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Paragon_AccountsEntities : DbContext
    {
        public Paragon_AccountsEntities()
            : base("name=Paragon_AccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<pr_Accounts_GenerateBordeaux_Result> pr_Accounts_GenerateBordeaux(string insco)
        {
            var inscoParameter = insco != null ?
                new ObjectParameter("Insco", insco) :
                new ObjectParameter("Insco", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Accounts_GenerateBordeaux_Result>("pr_Accounts_GenerateBordeaux", inscoParameter);
        }
    }
}
